language: python
python:
  - 3.8.7
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage3 run --source=./ --omit="templates/*" --branch test.py
after_success:
  coveralls
deploy:
  provider: heroku
  api_key:
    secure: "PDr2nZAAoQFs1WnG+pPKG2NxZepYyKzMSbZS2mNQq0Wo35gZGNktMd21dgO/JiNDkd9vuap1RcOwa1SjxxJEoOwi349fd6e05VPPT84oN7vKCYVKYMwUrYeqNsHhqkBbiuR7oAQ0gNIx8YgxpoPa2WmHR/QpicdL3efGOH/VMEm6S3o4riNOPth5kxsG+UIWS4nddtgSSt/vFhbzjFpZ1s8v5ywaLDywm1Mxwg+QtNtYV9TfZ8Cf9PF3fteZ7B/Ep+LivJhHL47Iooan3Rxxy9/sqANGoJdeBzUaOizYOyO+0hJzBMR+iNJpdL1szDKyoQVRGhUDNuGNoX/GC0yQJjbvTmX72IUSdq+HzAFkQ5f6ZVfkP8a9JAyVw/v2xIn+Ga7H4ZVd9vtPygHA/CyhKhFPMEg3+hUTKOxlHfGixza3B9g94K9yAf/EraoILgaadqAZ5Z2D6lgkVWoTbrfi6A1KQ/sBtHbvxf4y6svRYCWt6LO5BIbHCUBqCSnv7ExmSBxZSByzxWy3jA9ys6T1DDXTRpAwW95YJ1OwQzgwzMf/NZ3G9p4P/fu089Se0Nf7a7pekqvWwkvgG/BvS88L5GdPMrOZkFjLEfBqj/Qd7491KCcZULGQFBOXeXXa/Ov6D5XEMHxR0wXtq2azm6zv9g0qB1n7CqWarYBklBIjJaE="
  app: line-bot-reminder
  on:
    repo: KentHan/line-bot-reminder
    branch: master