language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run --source=./ --omit="templates/*" test.py
after_success:
  coveralls
deploy:
  provider: heroku
  api_key:
    secure: f7a3f16c-2239-4aba-bb83-513814ed661e