language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run --source=./ --omit="templates/*" --branch test.py
after_success:
  coveralls
deploy:
  provider: heroku
  api_key:
    secure: f7a3f16c-2239-4aba-bb83-513814ed661e
  app: line-bot-reminder
  on:
    repo: KentHan/line-bot-reminder
    branch: master

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: ${COVERITY_SCAN_TOKEN}

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "KentHan/line-bot-reminder"
      description: "<Your project description here>"
    notification_email: kenthan.tw@gmail.com
    build_command_prepend: ""
    build_command: "--no-command --fs-capture-search ./ --fs-capture-search-exclude-regex ./static"
    branch_pattern: coverity_scan
